# Generated by Django 4.0.8 on 2023-02-06 09:48

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=64, unique=True, validators=[core.validators.OneOfTwoValidator(field='Название тэга')], verbose_name='Тэг'),
        ),
    ]
