# Generated by Django 4.0.8 on 2023-02-05 06:20

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_myuser_first_name_alter_myuser_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(help_text='Обязательно для заполнения. Максимум 32 букв.', max_length=32, validators=[core.validators.OneOfTwoValidator(field='Имя')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(help_text='Обязательно для заполнения. Максимум 32 букв.', max_length=32, validators=[core.validators.OneOfTwoValidator(field='Фамилия')], verbose_name='Фамилия'),
        ),
    ]
