# Generated by Django 4.0.8 on 2023-02-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_myuser_first_name_alter_myuser_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='password',
            field=models.CharField(help_text='Обязательно для заполнения. Максимум 32 букв.', max_length=128, verbose_name='Пароль'),
        ),
    ]
