# Generated by Django 4.0.8 on 2023-02-05 08:46

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_myuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(help_text='Обязательно для заполнения. Максимум 32 букв.', max_length=32, validators=[core.validators.OneOfTwoValidator(field='Имя', first_regex='[^а-яёА-ЯЁ -]+', second_regex='[^a-zA-Z -]+')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(help_text='Обязательно для заполнения. Максимум 32 букв.', max_length=32, validators=[core.validators.OneOfTwoValidator(field='Фамилия', first_regex='[^а-яёА-ЯЁ -]+', second_regex='[^a-zA-Z -]+')], verbose_name='Фамилия'),
        ),
    ]
